function run_plots_fcn(Kinematics, run1_time_samples,...
    run1_q1_desired_scaled, run1_q2_desired_scaled, run1_A_all_pred)
%This function creates the following three plots:
% 1: 'Desired joint angles' plot
% 2: 'Kinematics of the desired trajectory' plot
% 3: 'Predicted activation values for the desired kinematics' plot

figure();plot(run1_time_samples, run1_q1_desired_scaled, run1_time_samples,...
    run1_q2_desired_scaled); xlabel('time(s)');ylabel('angle');...
    title('Desired joint anlges');legend('q_1','q_2');
figure();plot(run1_time_samples, Kinematics);...
    xlabel('time(s)');...
    ylabel('amplitudes');...
    title('Kinematics of the desired trajectory')
    legend('q_1', 'dq_1', 'ddq_1', 'q_2', 'dq_2', 'ddq_2')
figure();plot(run1_time_samples, run1_A_all_pred);...
    xlabel('time(s)');...
    ylabel('activation value (8bit:0-255)');...
    title('Predicted activation values for the desired kinematics');...
    legend('Motor 1','Motor 2', 'Motor 3');
end

